### ISSUE TITLE
unit test test_model fails on arm

### ISSUE THREAD

**Issue by toeklk** [toeklk/orocos-bayesian-filtering#10]
See http://bugs.orocos.org/show_bug.cgi?id=1062 (submitted by @morxa )

           Summary: unit test test_model fails on arm
           Product: BFL
           Version: trunk
          Platform: Other
        OS/Version: All
            Status: NEW
          Severity: normal
          Priority: P3
         Component: tests
        AssignedTo: bfl@lists.mech.kuleuven.be
        ReportedBy: hofmann@kbsg.rwth-aachen.de
                CC: bfl@lists.mech.kuleuven.be
   Estimated Hours: 0.0

The unit test test_model fails on arm architectures with the following error:
5: Test command: /builddir/build/BUILD/orocos-bfl-0.8.0/tests/test_model
5: Test timeout computed to be: 9.99988e+06
5: .F..
5:
5: model_test.cpp:99:Assertion
5: Test name: ModelTest::testDiscreteSystemModel
5: equality assertion failed
5: - Expected: 0.98
5: - Actual  : 0.005
5:
5: Failures !!!
5: Run: 3   Failure total: 1   Failures: 1   Errors: 0
5/8 Test #5: test_model .......................***Failed    0.02 sec

The complete build logfile is available here:
https://kojipkgs.fedoraproject.org//work/tasks/5337/9915337/build.log

**Comment by toeklk** [comment]
The same issue occurs on aarch64, see
https://bugzilla.redhat.com/show_bug.cgi?id=1346049 for more information.

**Comment by toeklk** [comment]
Could be fixed by https://github.com/toeklk/orocos-bayesian-filtering/commit/6c4534c73eb7dcade6b04d2ea4352de4a7a71b63 
Could you check if you can still reproduce this using master-head

**Comment by morxa** [comment]
Yes, builds are succeeding on arm and aarch64: https://koji.fedoraproject.org/koji/taskinfo?taskID=27293719

I think this issue can be closed.

**Comment by toeklk** [comment]
Thanks for checking!
