### ISSUE TITLE

    Build failure with Clang in mixtureParticleFilter.cpp
  

### ISSUE THREAD

**Issue by toeklk** [toeklk/orocos-bayesian-filtering#29]
migrated from Bugzilla [#1029](http://bugs.orocos.org/show_bug.cgi?id=1029)
status NEW severity *normal* in component *core* for *---*
Reported in version *trunk* on platform *All*
Assigned to: BFL mailinglist

Original attachment names and IDs:
- _[bfl-mixtureParticleFilter-bugfix.patch](http://bugs.orocos.org//attachment.cgi?id=860)_ (ID 860)

On 2013-05-23 18:59:20 +0200,  wrote:

> 
>       Created attachment 860 Bugfix patch When compiling BFL with clang, I get this error: /tmp/bfl/src/filter/mixtureParticleFilter.cpp:105:27: error: member reference base type 'Mixture() *' is not a structure or union for(int i =0 ; i ampersandlt; prior.NumComponentsGet() ; i++) ~~~~~^~~~~~~~~~~~~~~~~ /tmp/bfl/src/filter/mixtureParticleFilter.cpp:111:27: error: member reference base type 'Mixture() *' is not a structure or union for(int i =0 ; i ampersandlt; prior.NumComponentsGet() ; i++) ~~~~~^~~~~~~~~~~~~~~~~ /tmp/bfl/src/filter/mixtureParticleFilter.cpp:113:32: error: member reference base type 'Mixture() *' is not a structure or union _old_samplesVec[i] = (prior.ComponentGet(i)->ListOfSamplesGet()); ~~~~~^~~~~~~~~~~~~ 3 errors generated. The attached patch fixes this bug.
>

**Comment by kunaltyagi** [comment]
I can't reproduce this. Also, this patch is redundant. @toeklk: You can close this

**Comment by toeklk** [comment]
Confirmed, I can now also build with clang without errors.  Thx for checking!

```
[kgad@FM00022 ~/git/orocos-bayesian-filtering/orocos_bfl/build-clang]$  
 clang --version
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```
