### ISSUE TITLE
#define DEFAULT conflicts with OpenCV

### ISSUE THREAD

**Issue by toeklk** [toeklk/orocos-bayesian-filtering#30]
migrated from Bugzilla [#1069](http://bugs.orocos.org/show_bug.cgi?id=1069)
status NEW severity *enhancement* in component *core* for *---*
Reported in version *trunk* on platform *All*
Assigned to: BFL mailinglist

On 2016-09-01 14:59:46 +0200,  wrote:

> 
>       #define DEFAULT 0 in pdf.h line 47 causes trouble when using in combination with opencv, due to DEFAULT being used as enumeration item (e.g. in features2d.hpp)
>

**Comment by kunaltyagi** [comment]
Fixed by #38. Can close now
