### ISSUE TITLE
discreteCondPdf.ProbabilityGet() test fails on Mac OS X

### ISSUE THREAD

**Issue by toeklk** [toeklk/orocos-bayesian-filtering#4]
Output of make check on Mac OS X (Sierra, verified using both boost and eigen matrix libraries)

5: Test command: /Users/kgad/git/orocos-bayesian-filtering/orocos_bfl/build-default/tests/test_model
5: Test timeout computed to be: 9.99988e+06
5: .F..
5: 
5: /Users/kgad/git/orocos-bayesian-filtering/orocos_bfl/tests/model_test.cpp:99: Assertion
5: Test name: ModelTest::testDiscreteSystemModel
5: equality assertion failed
5: - Expected: 0.98
5: - Actual  : 0.005
5: 
5: Failures !!!
5: Run: 3   Failure total: 1   Failures: 1   Errors: 0
5/7 Test #5: test_model .......................***Failed    0.02 sec

**Comment by kunaltyagi** [comment]
Reproduced on x86_64 Ubuntu 16.04, Kernel 4.13, with Boost and Eigen matrix library.

Also, could we modify the FindMATRIX.cmake so it searches more on the lines of FindEigen.cmake that ROS provides by default?

**Comment by toeklk** [comment]
Thx for the report!  From a little google search, it seems like the default travis builder still uses ubuntu trusty.  Could you specify the versions of boost and eigen you are using?

Regarding you second remark, was that solved by https://github.com/toeklk/orocos-bayesian-filtering/pull/37 ? If not I suggest you open a new issue for that (not to "pollute" this one)

**Comment by toeklk** [comment]
For the record : Travis issue regarding ubuntu 16.04 is at https://github.com/travis-ci/travis-ci/issues/5821

**Comment by toeklk** [comment]
Seems to be an (actually 2) error(s) in the test, rather than an error in the code...  Please reopen if you can still reproduce it on your side!
