### ISSUE TITLE
Must orocos-bayesian-filtering rely on ROS?

### ISSUE THREAD

**Issue by jiapei100** [toeklk/orocos-bayesian-filtering#41]
Hi, I wonder if orocos-bayesian-filtering can be indepentent from ROS?
At least, from the begining of building?
In **CMakeLists.txt** , 
```
include($ENV{ROS_ROOT}/core/rosbuild/rosbuild.cmake)
```

That really....

Cheers
Pei

**Comment by toeklk** [comment]
Hi Pei,

Yes it can!
You can perfectly use BFL perfectly without ROS (or orocos).  Just build BFL from the subfolder orocos_bfl, ie. something like
```
[kgad@FM00022 ~/git/orocos-bayesian-filtering]$  
 cd orocos_bfl/
[kgad@FM00022 ~/git/orocos-bayesian-filtering/orocos_bfl]$  
 mkdir build-mybuildvariant
[kgad@FM00022 ~/git/orocos-bayesian-filtering/orocos_bfl]$  
 ccmake ..
```
 At least, that is why I do all the time :-)

Makes sense?

**Comment by toeklk** [comment]
Please reopen if you found the answer insufficient!
