### ISSUE TITLE
‘SampleMthd’ is not a class or namespace

### ISSUE THREAD

**Issue by UyaSong** [toeklk/orocos-bayesian-filtering#54]
Hi, I want to use orocos-bfl instead of ros-kinetic-bfl in my ROS1 project. But when compiling, it comes out with the error: ‘SampleMthd’ is not a class or namespace. However, I didn't meet this problem when using ros-kinetic-bfl. It's quite conflicting to me. Any solution or idea would be grateful.

**Comment by UyaSong** [comment]
the “enum class

**Comment by toeklk** [comment]
Not relevant anymore?

**Comment by UyaSong** [comment]
Well, it's my mistake, the scoped enumeration needs to add compiler option -std=c++11. In ros-kinetic-bfl the ‘SampleMthd’ is unscoped enumeration.
